# Generated by Django 5.1.6 on 2025-03-15 07:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_user', '0002_userprofile_role'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('Fashion', 'Fashion'), ('Phones & Tablets', 'Phones & Tablets'), ('Home & Office', 'Home & Office'), ('Electronics', 'Electronics'), ('Computing', 'Computing'), ('Heath & Beauty', 'Heath & Beauty'), ('Groceries', 'Groceries'), ('Sports & Fitness', 'Sports & Fitness'), ('Baby Products', 'Baby Products'), ('Automotive', 'Automotive')], max_length=255)),
                ('description', models.TextField(blank=True, max_length=1000, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('instock', 'instock'), ('outstock', 'outstock')], default='instock', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProductImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='Ecommerce_user.product')),
            ],
        ),
    ]
