# Generated by Django 5.1.6 on 2025-03-15 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_user', '0004_product_seller'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
