# Generated by Django 5.1.6 on 2025-03-15 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_user', '0005_userprofile_views'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='views',
        ),
        migrations.AddField(
            model_name='product',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
