# Generated by Django 5.1.6 on 2025-03-18 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Ecommerce_user', '0007_slideshow_alter_productimage_product_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='slideshow',
            name='description',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='slideshow',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
